import = ["~/.config/alacritty/nightfox.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 14.0

[colors]
draw_bold_text_with_bright_colors = true
