[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[aws]
disabled = true

[conda]
symbol = " "
ignore_base = false

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[nodejs]
symbol = " "

[openstack]
disabled = true

[package]
symbol = " "

[python]
symbol = " "
python_binary = ["python3", "python", "python2"]

[ruby]
symbol = " "

[rust]
symbol = " "
