# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true
