[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[haskell]
disabled = true

[aws]
disabled = true

[conda]
symbol = " "
ignore_base = false

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
