# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

foreground #A1B0B8
background #151515

# background_opacity         1.0
# dynamic_background_opacity no

# dim_opacity 0.75

# selection_foreground #000000
# selection_background #FFFACD

#: black
color0 #252525
color8 #708284

#: red
color1 #FF5252
color9 #FF5252

#: green
color2  #C3D82C
color10 #C3D82C

#: yellow
color3  #FFC135
color11 #FFC135

#: blue
color4  #42A5F5
color12 #42A5F5

#: magenta
color5  #D81B60
color13 #D81B60

#: cyan
color6  #00ACC1
color14 #00ACC1

#: white
color7  #F5F5F5
color15 #F5F5F5

