version: 2
root-markers:
  - .git/

tools:
  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --quiet -'
    format-stdin: true

  cmake-format: &cmake-format
    format-command: 'cmake-format -'
    format-stdin: true

  cmake-lint: &cmake-lint
    lint-command: 'cmake-lint --suppress-decorations'
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'

  luafmt: &luafmt
    format-command: 'lua-format'
    format-stdin: true

  xmllint: &xmllint
    format-command: 'xmllint --format -'
    format-stdin: true

languages:
  python:
    - <<: *python-black
    - <<: *python-isort

  cmake:
    - <<: *cmake-format
    - <<: *cmake-lint

  lua:
    - <<: *luafmt

  xml:
    - <<: *xmllint
