#!/usr/bin/env bash

set -euo pipefail

if type nitrogen >/dev/null; then
  nitrogen --restore >/dev/null 2>&1
fi

if type polybar-msg >/dev/null; then
  sleep 1
  # Wait for all polybar instances to die
  while pgrep -u "$UID" -x polybar >/dev/null; do
    # Kill all polybar instances
    polybar-msg cmd quit
    sleep 0.5
  done

  # The monitor in which to output the main bar
  # Prefer whatever xrandr thinks is the primary monitor
  primary_monitor="$(polybar -m | awk 'BEGIN { FS = ":" }; /primary/ { print $1 };')"
  tray_output="$primary_monitor"

  # Start a bar for each monitor
  while read -r m; do
    bar=""
    if [[ "$m" == "$tray_output" ]]; then
      bar="main"
    else
      bar="secondary"
    fi
    MONITOR=$m polybar --reload "$bar" </dev/null >/var/tmp/polybar-"$m".log 2>&1 &
    disown
  done < <(polybar -m | cut -d ':' -f 1)
fi

if type xkbcomp >/dev/null; then
  XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
  log_dir=$XDG_STATE_HOME/xkbconfig
  mkdir -p "$log_dir"
  log_file=$log_dir/keymap.log

  XKB_CONFIG_DIR=$XDG_CONFIG_HOME/xkb

  xkbcomp -I"$XKB_CONFIG_DIR" "$XKB_CONFIG_DIR"/keymap/custom "$DISPLAY" >"$log_file" 2>&1
fi

if type xinput >/dev/null; then
  touchpad_dev='DELL08AF:00 06CB:76AF Touchpad'
  tapping_enabled='libinput Tapping Enabled'
  tapping_drag_enabled='libinput Tapping Drag Enabled'
  tapping_natural_scrolling_enabled='libinput Natural Scrolling Enabled'

  xinput set-prop "$touchpad_dev" "$tapping_enabled" 1
  xinput set-prop "$touchpad_dev" "$tapping_drag_enabled" 1
  xinput set-prop "$touchpad_dev" "$tapping_natural_scrolling_enabled" 1
fi

# vim: set ft=bash
