#!/usr/bin/env bash

if type nitrogen > /dev/null; then
  nitrogen --restore > /dev/null 2>&1
fi

if type polybar-msg > /dev/null; then
  # Kill all polybar instances
  polybar-msg cmd quit

  # Wait for all polybar instances to die
  while pgrep -u $UID -x polybar > /dev/null; do
    sleep 0.5
  done

  # The monitor in which to output the main bar
  if $(polybar -m | grep -q "eDP1"); then
    tray_output=eDP1
  else
    tray_output=$(polybar -m | head -n1 | cut -d ":" -f 1)
  fi

  # Start a bar for each monitor
  for m in $(polybar -m | cut -d ':' -f 1); do
    bar=""
    if [[ $m == $tray_output ]]; then
      bar="main"
    else
      bar="secondary"
    fi
    MONITOR=$m polybar --reload $bar </dev/null >/var/tmp/polybar-$m.log 2>&1 &
    disown
  done
fi

if type xkbcomp > /dev/null; then
  XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
  log_dir=$XDG_STATE_HOME/xkbconfig
  mkdir -p $log_dir
  log_file=$log_dir/keymap.log

  XKB_CONFIG_DIR=$XDG_CONFIG_HOME/xkb

  xkbcomp -I$XKB_CONFIG_DIR $XKB_CONFIG_DIR/keymap/custom $DISPLAY > $log_file 2>&1
fi
