#!/usr/bin/env bash

set -euo pipefail

function launch() {
  eval "$1" </dev/null &
  disown
}

# Move i3wm autostart here
declare -a _autostart_daemons=(
  picom        # Compositor
  light-locker # locker
  # dunst        # notification daemon
  lxpolkit
  autotiling # i3wm tiling plugin
  xsettingsd # X Settings daemon
)
for daemon_exe in "${_autostart_daemons[@]}"; do
  if type "$daemon_exe" >/dev/null; then
    if ! pgrep -u "$UID" -x "$daemon_exe" >/dev/null; then
      launch "$daemon_exe"
    fi
  fi
done

# Set wallpaper
if type feh >/dev/null; then
  feh --bg-scale "$HOME"/.config/i3/backgrounds/losangeles.png >/dev/null 2>&1
fi

# Launch bar
if type polybar-msg >/dev/null; then
  sleep 1
  # Wait for all polybar instances to die
  while pgrep -u "$UID" -x polybar >/dev/null; do
    # Kill all polybar instances
    polybar-msg cmd quit
    sleep 0.5
  done

  # The monitor in which to output the main bar
  # Prefer whatever xrandr thinks is the primary monitor
  primary_monitor="$(polybar -m | awk 'BEGIN { FS = ":" }; /primary/ { print $1 };')"
  tray_output="$primary_monitor"

  # Start a bar for each monitor
  while read -r m; do
    bar=""
    if [[ "$m" == "$tray_output" ]]; then
      bar="main"
    else
      bar="secondary"
    fi
    MONITOR=$m polybar --reload "$bar" </dev/null >/var/tmp/polybar-"$m".log 2>&1 &
    disown
  done < <(polybar -m | cut -d ':' -f 1)
fi

if type xinput >/dev/null; then
  xinput list --name-only | grep 'Touchpad' | {
    while read -r touchpad_dev; do
      tapping_enabled='libinput Tapping Enabled'
      tapping_drag_enabled='libinput Tapping Drag Enabled'
      tapping_natural_scrolling_enabled='libinput Natural Scrolling Enabled'

      xinput set-prop "$touchpad_dev" "$tapping_enabled" 1
      xinput set-prop "$touchpad_dev" "$tapping_drag_enabled" 1
      xinput set-prop "$touchpad_dev" "$tapping_natural_scrolling_enabled" 1
    done
  }
fi
