#!/usr/bin/env bash

XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
log_dir=$XDG_STATE_HOME/xkbconfig
mkdir -p $log_dir
log_file=$log_dir/keymap.log

XKB_CONFIG_DIR=$XDG_CONFIG_HOME/xkb

xkbcomp -I$XKB_CONFIG_DIR $XKB_CONFIG_DIR/keymap/custom $DISPLAY > $log_file 2>&1

