#!/bin/bash

source ${HOME}/.cargo/env
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"



